name: spoonacular
description: "Flutter Clean Architecture"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  dio: ^5.6.0
  pretty_dio_logger:
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.1
  cached_network_image: ^3.4.1
  auto_route: ^10.0.1
  encrypt: ^5.0.3
  drift: ^2.25.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  path: ^1.9.0
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner:
  riverpod_lint: ^2.6.2
  custom_lint: ^0.7.1
  riverpod_generator:
  auto_route_generator:
  drift_dev: ^2.25.2
  flutter_flavorizr: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/